package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        maven {
            goals = "clean compile test"
            mavenVersion = defaultProvidedVersion()
        }
        script {
            name = "hello world hello"
            scriptContent = """echo "hello world from kotlin""""
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            scriptContent = """echo "hello world from kotlin again""""
        }
    }
}
